### ISSUE TITLE
Is it possible to transmit the generated data in real time and decode the captured data?

### ISSUE THREAD

**Issue by RashVm** [abdulkarimgizzini/Deep-Learning-Based-Channel-Estimation-Schemes-for-IEEE-802.11p-Standard#1]
I am trying to transmit data in real time and decode it back using the matlab code.

1)Initially   I am saving     '**Random_permutation_Vector'** ((1x9600)% Permutation vector),    **'Bits_Stream_Coded'** ((4800x1)% Bits Stream Generation), and **'IFFT_Data_CP_Preamble_Coded'**(80x102)) as a mat files in simulation,

2)I am transmitting **'IFFT_Data_CP_Preamble_Coded'**(reshaped as 8160x1) using RF (without any modification) and captured in IIo osilloscope

3) Then I am reshaping the captured data as (80x102)

4) Then I fed  back all the saved data(loading back again to the exact point where it is taken) and captured data again into the simulation.But  I am not able decode data

Can you please help me in this,

Thank you.

**Comment by abdulkarimgizzini** [comment]
Good morning,
Thank you for your interest in my research work. Actually, we tried this before and it worked fine. Kindly, could you please ensure that you are using the same Random_permutation_Vector in both interleaving and deinterleaving operations?. 
In all cases, we can schedule an online meeting and discuss this issue.

**Comment by RashVm** [comment]
Thank you for your response,

I am sure that I am using same Random_permutation_Vector in both interleaving and deinterleaving operations, even I tried just importing the saved data, In that case it is working fine.

But when I use the real time captured data, it is not decoding.

I have attached my capture data along with 'Random_permutation_Vector' and 'Bits_Stream_Coded'.
if it is possible please try with these data 

Thank you for inviting me to the online meeting. I am happy to be doing that.  

Thank you.

[data.zip](https://github.com/abdulkarimgizzini/Deep-Learning-Based-Channel-Estimation-Schemes-for-IEEE-802.11p-Standard/files/8133032/data.zip)

**Comment by RashVm** [comment]
Hey 

I am circling back to ensure you received my previous comment .
Are you still available ? .

Regards,

Thank you.
